// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/crypto_api.dart';
import 'api/http_api.dart';
import 'api/init.dart';
import 'api/module_api.dart';
import 'api/property_api.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'modules/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
    await api.crateApiInitInitFrb();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 174762568;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_comics',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiModuleApiCallModuleFunction({
    required String moduleId,
    required String funcName,
    required String argsJson,
  });

  Future<BigInt> crateApiPropertyApiClearModuleProperties({
    required String moduleId,
  });

  String crateApiCryptoApiCryptoBase64Decode({required String data});

  String crateApiCryptoApiCryptoBase64Encode({required String data});

  String crateApiCryptoApiCryptoHexDecode({required String data});

  String crateApiCryptoApiCryptoHexEncode({required String data});

  String crateApiCryptoApiCryptoMd5({required String data});

  String crateApiCryptoApiCryptoMd5Bytes({required List<int> data});

  String crateApiCryptoApiCryptoSha256({required String data});

  String crateApiCryptoApiCryptoSha256Bytes({required List<int> data});

  String crateApiCryptoApiCryptoSha512({required String data});

  Future<void> crateApiPropertyApiDeleteProperty({
    required String moduleId,
    required String key,
  });

  String? crateApiInitGetCacheDir();

  Future<List<Category>> crateApiModuleApiGetCategories({
    required String moduleId,
  });

  Future<ChapterImages> crateApiModuleApiGetChapterImages({
    required String moduleId,
    required String comicId,
    required String chapterId,
  });

  Future<ComicDetail> crateApiModuleApiGetComicDetail({
    required String moduleId,
    required String comicId,
  });

  Future<ComicListResponse> crateApiModuleApiGetComicList({
    required String moduleId,
    required String categoryId,
    required int page,
  });

  Future<List<ModuleInfo>> crateApiModuleApiGetModules();

  String? crateApiInitGetModulesDir();

  String? crateApiInitGetRootPath();

  String crateApiSimpleGreet({required String name});

  Future<Uint8List> crateApiHttpApiHttpDownload({
    required String url,
    required Map<String, String> headers,
  });

  Future<HttpResponseDto> crateApiHttpApiHttpGet({
    required String url,
    required Map<String, String> headers,
  });

  Future<HttpResponseDto> crateApiHttpApiHttpPost({
    required String url,
    required Map<String, String> headers,
    String? body,
  });

  Future<HttpResponseDto> crateApiHttpApiHttpRequest({
    required String url,
    required String method,
    required Map<String, String> headers,
    String? body,
    required BigInt timeoutSecs,
  });

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiInitInitApplication({required String rootPath});

  Future<void> crateApiInitInitFrb();

  bool crateApiInitIsInitialized();

  Future<List<PropertyItem>> crateApiPropertyApiListProperties({
    required String moduleId,
  });

  Future<List<PropertyItem>> crateApiPropertyApiListPropertiesByPrefix({
    required String moduleId,
    required String prefix,
  });

  Future<void> crateApiModuleApiLoadModule({required String moduleId});

  Future<String?> crateApiPropertyApiLoadProperty({
    required String moduleId,
    required String key,
  });

  Future<ModuleInfo> crateApiModuleApiRegisterModule({
    required String moduleId,
  });

  Future<void> crateApiPropertyApiSaveProperty({
    required String moduleId,
    required String key,
    required String value,
  });

  Future<List<ModuleInfo>> crateApiModuleApiScanAndRegisterModules();

  Future<ComicListResponse> crateApiModuleApiSearchComics({
    required String moduleId,
    required String keyword,
    required int page,
  });

  Future<void> crateApiModuleApiSetModuleEnabled({
    required String moduleId,
    required bool enabled,
  });

  Future<void> crateApiModuleApiUnloadModule({required String moduleId});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiModuleApiCallModuleFunction({
    required String moduleId,
    required String funcName,
    required String argsJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleId, serializer);
          sse_encode_String(funcName, serializer);
          sse_encode_String(argsJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModuleApiCallModuleFunctionConstMeta,
        argValues: [moduleId, funcName, argsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiCallModuleFunctionConstMeta =>
      const TaskConstMeta(
        debugName: "call_module_function",
        argNames: ["moduleId", "funcName", "argsJson"],
      );

  @override
  Future<BigInt> crateApiPropertyApiClearModuleProperties({
    required String moduleId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPropertyApiClearModulePropertiesConstMeta,
        argValues: [moduleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertyApiClearModulePropertiesConstMeta =>
      const TaskConstMeta(
        debugName: "clear_module_properties",
        argNames: ["moduleId"],
      );

  @override
  String crateApiCryptoApiCryptoBase64Decode({required String data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoApiCryptoBase64DecodeConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoApiCryptoBase64DecodeConstMeta =>
      const TaskConstMeta(
        debugName: "crypto_base64_decode",
        argNames: ["data"],
      );

  @override
  String crateApiCryptoApiCryptoBase64Encode({required String data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoApiCryptoBase64EncodeConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoApiCryptoBase64EncodeConstMeta =>
      const TaskConstMeta(
        debugName: "crypto_base64_encode",
        argNames: ["data"],
      );

  @override
  String crateApiCryptoApiCryptoHexDecode({required String data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoApiCryptoHexDecodeConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoApiCryptoHexDecodeConstMeta =>
      const TaskConstMeta(debugName: "crypto_hex_decode", argNames: ["data"]);

  @override
  String crateApiCryptoApiCryptoHexEncode({required String data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoApiCryptoHexEncodeConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoApiCryptoHexEncodeConstMeta =>
      const TaskConstMeta(debugName: "crypto_hex_encode", argNames: ["data"]);

  @override
  String crateApiCryptoApiCryptoMd5({required String data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoApiCryptoMd5ConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoApiCryptoMd5ConstMeta =>
      const TaskConstMeta(debugName: "crypto_md5", argNames: ["data"]);

  @override
  String crateApiCryptoApiCryptoMd5Bytes({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoApiCryptoMd5BytesConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoApiCryptoMd5BytesConstMeta =>
      const TaskConstMeta(debugName: "crypto_md5_bytes", argNames: ["data"]);

  @override
  String crateApiCryptoApiCryptoSha256({required String data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoApiCryptoSha256ConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoApiCryptoSha256ConstMeta =>
      const TaskConstMeta(debugName: "crypto_sha256", argNames: ["data"]);

  @override
  String crateApiCryptoApiCryptoSha256Bytes({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoApiCryptoSha256BytesConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoApiCryptoSha256BytesConstMeta =>
      const TaskConstMeta(debugName: "crypto_sha256_bytes", argNames: ["data"]);

  @override
  String crateApiCryptoApiCryptoSha512({required String data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoApiCryptoSha512ConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoApiCryptoSha512ConstMeta =>
      const TaskConstMeta(debugName: "crypto_sha512", argNames: ["data"]);

  @override
  Future<void> crateApiPropertyApiDeleteProperty({
    required String moduleId,
    required String key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleId, serializer);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPropertyApiDeletePropertyConstMeta,
        argValues: [moduleId, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertyApiDeletePropertyConstMeta =>
      const TaskConstMeta(
        debugName: "delete_property",
        argNames: ["moduleId", "key"],
      );

  @override
  String? crateApiInitGetCacheDir() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitGetCacheDirConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitGetCacheDirConstMeta =>
      const TaskConstMeta(debugName: "get_cache_dir", argNames: []);

  @override
  Future<List<Category>> crateApiModuleApiGetCategories({
    required String moduleId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_category,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModuleApiGetCategoriesConstMeta,
        argValues: [moduleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiGetCategoriesConstMeta =>
      const TaskConstMeta(debugName: "get_categories", argNames: ["moduleId"]);

  @override
  Future<ChapterImages> crateApiModuleApiGetChapterImages({
    required String moduleId,
    required String comicId,
    required String chapterId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleId, serializer);
          sse_encode_String(comicId, serializer);
          sse_encode_String(chapterId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chapter_images,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModuleApiGetChapterImagesConstMeta,
        argValues: [moduleId, comicId, chapterId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiGetChapterImagesConstMeta =>
      const TaskConstMeta(
        debugName: "get_chapter_images",
        argNames: ["moduleId", "comicId", "chapterId"],
      );

  @override
  Future<ComicDetail> crateApiModuleApiGetComicDetail({
    required String moduleId,
    required String comicId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleId, serializer);
          sse_encode_String(comicId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_comic_detail,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModuleApiGetComicDetailConstMeta,
        argValues: [moduleId, comicId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiGetComicDetailConstMeta =>
      const TaskConstMeta(
        debugName: "get_comic_detail",
        argNames: ["moduleId", "comicId"],
      );

  @override
  Future<ComicListResponse> crateApiModuleApiGetComicList({
    required String moduleId,
    required String categoryId,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleId, serializer);
          sse_encode_String(categoryId, serializer);
          sse_encode_i_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_comic_list_response,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModuleApiGetComicListConstMeta,
        argValues: [moduleId, categoryId, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiGetComicListConstMeta =>
      const TaskConstMeta(
        debugName: "get_comic_list",
        argNames: ["moduleId", "categoryId", "page"],
      );

  @override
  Future<List<ModuleInfo>> crateApiModuleApiGetModules() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_module_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModuleApiGetModulesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiGetModulesConstMeta =>
      const TaskConstMeta(debugName: "get_modules", argNames: []);

  @override
  String? crateApiInitGetModulesDir() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitGetModulesDirConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitGetModulesDirConstMeta =>
      const TaskConstMeta(debugName: "get_modules_dir", argNames: []);

  @override
  String? crateApiInitGetRootPath() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitGetRootPathConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitGetRootPathConstMeta =>
      const TaskConstMeta(debugName: "get_root_path", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<Uint8List> crateApiHttpApiHttpDownload({
    required String url,
    required Map<String, String> headers,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_Map_String_String_None(headers, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHttpApiHttpDownloadConstMeta,
        argValues: [url, headers],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHttpApiHttpDownloadConstMeta =>
      const TaskConstMeta(
        debugName: "http_download",
        argNames: ["url", "headers"],
      );

  @override
  Future<HttpResponseDto> crateApiHttpApiHttpGet({
    required String url,
    required Map<String, String> headers,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_Map_String_String_None(headers, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_http_response_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHttpApiHttpGetConstMeta,
        argValues: [url, headers],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHttpApiHttpGetConstMeta =>
      const TaskConstMeta(debugName: "http_get", argNames: ["url", "headers"]);

  @override
  Future<HttpResponseDto> crateApiHttpApiHttpPost({
    required String url,
    required Map<String, String> headers,
    String? body,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_Map_String_String_None(headers, serializer);
          sse_encode_opt_String(body, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_http_response_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHttpApiHttpPostConstMeta,
        argValues: [url, headers, body],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHttpApiHttpPostConstMeta => const TaskConstMeta(
    debugName: "http_post",
    argNames: ["url", "headers", "body"],
  );

  @override
  Future<HttpResponseDto> crateApiHttpApiHttpRequest({
    required String url,
    required String method,
    required Map<String, String> headers,
    String? body,
    required BigInt timeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(method, serializer);
          sse_encode_Map_String_String_None(headers, serializer);
          sse_encode_opt_String(body, serializer);
          sse_encode_u_64(timeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_http_response_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHttpApiHttpRequestConstMeta,
        argValues: [url, method, headers, body, timeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHttpApiHttpRequestConstMeta => const TaskConstMeta(
    debugName: "http_request",
    argNames: ["url", "method", "headers", "body", "timeoutSecs"],
  );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiInitInitApplication({required String rootPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rootPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInitInitApplicationConstMeta,
        argValues: [rootPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitInitApplicationConstMeta =>
      const TaskConstMeta(
        debugName: "init_application",
        argNames: ["rootPath"],
      );

  @override
  Future<void> crateApiInitInitFrb() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitInitFrbConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitInitFrbConstMeta =>
      const TaskConstMeta(debugName: "init_frb", argNames: []);

  @override
  bool crateApiInitIsInitialized() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitIsInitializedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitIsInitializedConstMeta =>
      const TaskConstMeta(debugName: "is_initialized", argNames: []);

  @override
  Future<List<PropertyItem>> crateApiPropertyApiListProperties({
    required String moduleId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_property_item,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPropertyApiListPropertiesConstMeta,
        argValues: [moduleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertyApiListPropertiesConstMeta =>
      const TaskConstMeta(debugName: "list_properties", argNames: ["moduleId"]);

  @override
  Future<List<PropertyItem>> crateApiPropertyApiListPropertiesByPrefix({
    required String moduleId,
    required String prefix,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleId, serializer);
          sse_encode_String(prefix, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_property_item,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPropertyApiListPropertiesByPrefixConstMeta,
        argValues: [moduleId, prefix],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertyApiListPropertiesByPrefixConstMeta =>
      const TaskConstMeta(
        debugName: "list_properties_by_prefix",
        argNames: ["moduleId", "prefix"],
      );

  @override
  Future<void> crateApiModuleApiLoadModule({required String moduleId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModuleApiLoadModuleConstMeta,
        argValues: [moduleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiLoadModuleConstMeta =>
      const TaskConstMeta(debugName: "load_module", argNames: ["moduleId"]);

  @override
  Future<String?> crateApiPropertyApiLoadProperty({
    required String moduleId,
    required String key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleId, serializer);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPropertyApiLoadPropertyConstMeta,
        argValues: [moduleId, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertyApiLoadPropertyConstMeta =>
      const TaskConstMeta(
        debugName: "load_property",
        argNames: ["moduleId", "key"],
      );

  @override
  Future<ModuleInfo> crateApiModuleApiRegisterModule({
    required String moduleId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_module_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModuleApiRegisterModuleConstMeta,
        argValues: [moduleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiRegisterModuleConstMeta =>
      const TaskConstMeta(debugName: "register_module", argNames: ["moduleId"]);

  @override
  Future<void> crateApiPropertyApiSaveProperty({
    required String moduleId,
    required String key,
    required String value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleId, serializer);
          sse_encode_String(key, serializer);
          sse_encode_String(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPropertyApiSavePropertyConstMeta,
        argValues: [moduleId, key, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertyApiSavePropertyConstMeta =>
      const TaskConstMeta(
        debugName: "save_property",
        argNames: ["moduleId", "key", "value"],
      );

  @override
  Future<List<ModuleInfo>> crateApiModuleApiScanAndRegisterModules() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_module_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModuleApiScanAndRegisterModulesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiScanAndRegisterModulesConstMeta =>
      const TaskConstMeta(debugName: "scan_and_register_modules", argNames: []);

  @override
  Future<ComicListResponse> crateApiModuleApiSearchComics({
    required String moduleId,
    required String keyword,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleId, serializer);
          sse_encode_String(keyword, serializer);
          sse_encode_i_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_comic_list_response,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModuleApiSearchComicsConstMeta,
        argValues: [moduleId, keyword, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiSearchComicsConstMeta =>
      const TaskConstMeta(
        debugName: "search_comics",
        argNames: ["moduleId", "keyword", "page"],
      );

  @override
  Future<void> crateApiModuleApiSetModuleEnabled({
    required String moduleId,
    required bool enabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleId, serializer);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModuleApiSetModuleEnabledConstMeta,
        argValues: [moduleId, enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiSetModuleEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "set_module_enabled",
        argNames: ["moduleId", "enabled"],
      );

  @override
  Future<void> crateApiModuleApiUnloadModule({required String moduleId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModuleApiUnloadModuleConstMeta,
        argValues: [moduleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleApiUnloadModuleConstMeta =>
      const TaskConstMeta(debugName: "unload_module", argNames: ["moduleId"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_string(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Category dco_decode_category(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Category(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      cover: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  Chapter dco_decode_chapter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Chapter(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      updateTime: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  ChapterImages dco_decode_chapter_images(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ChapterImages(
      chapterId: dco_decode_String(arr[0]),
      images: dco_decode_list_image_info(arr[1]),
    );
  }

  @protected
  ComicDetail dco_decode_comic_detail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ComicDetail(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      cover: dco_decode_String(arr[2]),
      author: dco_decode_opt_String(arr[3]),
      description: dco_decode_opt_String(arr[4]),
      status: dco_decode_opt_String(arr[5]),
      tags: dco_decode_list_String(arr[6]),
      chapters: dco_decode_list_chapter(arr[7]),
      updateTime: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  ComicListResponse dco_decode_comic_list_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ComicListResponse(
      comics: dco_decode_list_comic_simple(arr[0]),
      pageInfo: dco_decode_page_info(arr[1]),
    );
  }

  @protected
  ComicSimple dco_decode_comic_simple(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ComicSimple(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      cover: dco_decode_String(arr[2]),
      author: dco_decode_opt_String(arr[3]),
      updateInfo: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  HttpResponseDto dco_decode_http_response_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return HttpResponseDto(
      status: dco_decode_u_16(arr[0]),
      headers: dco_decode_Map_String_String_None(arr[1]),
      body: dco_decode_String(arr[2]),
      contentType: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ImageInfo dco_decode_image_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ImageInfo(
      url: dco_decode_String(arr[0]),
      width: dco_decode_opt_box_autoadd_i_32(arr[1]),
      height: dco_decode_opt_box_autoadd_i_32(arr[2]),
      headers: dco_decode_opt_Map_String_String_None(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Category> dco_decode_list_category(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_category).toList();
  }

  @protected
  List<Chapter> dco_decode_list_chapter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chapter).toList();
  }

  @protected
  List<ComicSimple> dco_decode_list_comic_simple(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_comic_simple).toList();
  }

  @protected
  List<ImageInfo> dco_decode_list_image_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_image_info).toList();
  }

  @protected
  List<ModuleInfo> dco_decode_list_module_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_module_info).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<PropertyItem> dco_decode_list_property_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_property_item).toList();
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  ModuleInfo dco_decode_module_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ModuleInfo(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      version: dco_decode_String(arr[2]),
      description: dco_decode_String(arr[3]),
      enabled: dco_decode_bool(arr[4]),
    );
  }

  @protected
  Map<String, String>? dco_decode_opt_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_Map_String_String_None(raw);
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  PageInfo dco_decode_page_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PageInfo(
      page: dco_decode_i_32(arr[0]),
      pageSize: dco_decode_i_32(arr[1]),
      total: dco_decode_opt_box_autoadd_i_32(arr[2]),
      hasMore: dco_decode_bool(arr[3]),
    );
  }

  @protected
  PropertyItem dco_decode_property_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PropertyItem(
      key: dco_decode_String(arr[0]),
      value: dco_decode_String(arr[1]),
    );
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  Category sse_decode_category(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_cover = sse_decode_opt_String(deserializer);
    return Category(id: var_id, name: var_name, cover: var_cover);
  }

  @protected
  Chapter sse_decode_chapter(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_updateTime = sse_decode_opt_String(deserializer);
    return Chapter(id: var_id, title: var_title, updateTime: var_updateTime);
  }

  @protected
  ChapterImages sse_decode_chapter_images(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chapterId = sse_decode_String(deserializer);
    var var_images = sse_decode_list_image_info(deserializer);
    return ChapterImages(chapterId: var_chapterId, images: var_images);
  }

  @protected
  ComicDetail sse_decode_comic_detail(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_cover = sse_decode_String(deserializer);
    var var_author = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_status = sse_decode_opt_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_chapters = sse_decode_list_chapter(deserializer);
    var var_updateTime = sse_decode_opt_String(deserializer);
    return ComicDetail(
      id: var_id,
      title: var_title,
      cover: var_cover,
      author: var_author,
      description: var_description,
      status: var_status,
      tags: var_tags,
      chapters: var_chapters,
      updateTime: var_updateTime,
    );
  }

  @protected
  ComicListResponse sse_decode_comic_list_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_comics = sse_decode_list_comic_simple(deserializer);
    var var_pageInfo = sse_decode_page_info(deserializer);
    return ComicListResponse(comics: var_comics, pageInfo: var_pageInfo);
  }

  @protected
  ComicSimple sse_decode_comic_simple(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_cover = sse_decode_String(deserializer);
    var var_author = sse_decode_opt_String(deserializer);
    var var_updateInfo = sse_decode_opt_String(deserializer);
    return ComicSimple(
      id: var_id,
      title: var_title,
      cover: var_cover,
      author: var_author,
      updateInfo: var_updateInfo,
    );
  }

  @protected
  HttpResponseDto sse_decode_http_response_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_u_16(deserializer);
    var var_headers = sse_decode_Map_String_String_None(deserializer);
    var var_body = sse_decode_String(deserializer);
    var var_contentType = sse_decode_String(deserializer);
    return HttpResponseDto(
      status: var_status,
      headers: var_headers,
      body: var_body,
      contentType: var_contentType,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  ImageInfo sse_decode_image_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_width = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_height = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_headers = sse_decode_opt_Map_String_String_None(deserializer);
    return ImageInfo(
      url: var_url,
      width: var_width,
      height: var_height,
      headers: var_headers,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Category> sse_decode_list_category(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Category>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_category(deserializer));
    }
    return ans_;
  }

  @protected
  List<Chapter> sse_decode_list_chapter(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Chapter>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chapter(deserializer));
    }
    return ans_;
  }

  @protected
  List<ComicSimple> sse_decode_list_comic_simple(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ComicSimple>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_comic_simple(deserializer));
    }
    return ans_;
  }

  @protected
  List<ImageInfo> sse_decode_list_image_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ImageInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_image_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<ModuleInfo> sse_decode_list_module_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ModuleInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_module_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<PropertyItem> sse_decode_list_property_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PropertyItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_property_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  ModuleInfo sse_decode_module_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_enabled = sse_decode_bool(deserializer);
    return ModuleInfo(
      id: var_id,
      name: var_name,
      version: var_version,
      description: var_description,
      enabled: var_enabled,
    );
  }

  @protected
  Map<String, String>? sse_decode_opt_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_Map_String_String_None(deserializer));
    } else {
      return null;
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PageInfo sse_decode_page_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_page = sse_decode_i_32(deserializer);
    var var_pageSize = sse_decode_i_32(deserializer);
    var var_total = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_hasMore = sse_decode_bool(deserializer);
    return PageInfo(
      page: var_page,
      pageSize: var_pageSize,
      total: var_total,
      hasMore: var_hasMore,
    );
  }

  @protected
  PropertyItem sse_decode_property_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    return PropertyItem(key: var_key, value: var_value);
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_category(Category self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.cover, serializer);
  }

  @protected
  void sse_encode_chapter(Chapter self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.updateTime, serializer);
  }

  @protected
  void sse_encode_chapter_images(ChapterImages self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.chapterId, serializer);
    sse_encode_list_image_info(self.images, serializer);
  }

  @protected
  void sse_encode_comic_detail(ComicDetail self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.cover, serializer);
    sse_encode_opt_String(self.author, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_opt_String(self.status, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_list_chapter(self.chapters, serializer);
    sse_encode_opt_String(self.updateTime, serializer);
  }

  @protected
  void sse_encode_comic_list_response(
    ComicListResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_comic_simple(self.comics, serializer);
    sse_encode_page_info(self.pageInfo, serializer);
  }

  @protected
  void sse_encode_comic_simple(ComicSimple self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.cover, serializer);
    sse_encode_opt_String(self.author, serializer);
    sse_encode_opt_String(self.updateInfo, serializer);
  }

  @protected
  void sse_encode_http_response_dto(
    HttpResponseDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.status, serializer);
    sse_encode_Map_String_String_None(self.headers, serializer);
    sse_encode_String(self.body, serializer);
    sse_encode_String(self.contentType, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_image_info(ImageInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_opt_box_autoadd_i_32(self.width, serializer);
    sse_encode_opt_box_autoadd_i_32(self.height, serializer);
    sse_encode_opt_Map_String_String_None(self.headers, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_category(List<Category> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_category(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chapter(List<Chapter> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chapter(item, serializer);
    }
  }

  @protected
  void sse_encode_list_comic_simple(
    List<ComicSimple> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_comic_simple(item, serializer);
    }
  }

  @protected
  void sse_encode_list_image_info(
    List<ImageInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_image_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_module_info(
    List<ModuleInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_module_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_property_item(
    List<PropertyItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_property_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_module_info(ModuleInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.version, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_bool(self.enabled, serializer);
  }

  @protected
  void sse_encode_opt_Map_String_String_None(
    Map<String, String>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_Map_String_String_None(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_page_info(PageInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.page, serializer);
    sse_encode_i_32(self.pageSize, serializer);
    sse_encode_opt_box_autoadd_i_32(self.total, serializer);
    sse_encode_bool(self.hasMore, serializer);
  }

  @protected
  void sse_encode_property_item(PropertyItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.value, serializer);
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
