// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/crypto_api.dart';
import 'api/http_api.dart';
import 'api/init.dart';
import 'api/module_api.dart';
import 'api/property_api.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'modules/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  Category dco_decode_category(dynamic raw);

  @protected
  Chapter dco_decode_chapter(dynamic raw);

  @protected
  ChapterImages dco_decode_chapter_images(dynamic raw);

  @protected
  ComicDetail dco_decode_comic_detail(dynamic raw);

  @protected
  ComicListResponse dco_decode_comic_list_response(dynamic raw);

  @protected
  ComicSimple dco_decode_comic_simple(dynamic raw);

  @protected
  HttpResponseDto dco_decode_http_response_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  ImageInfo dco_decode_image_info(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Category> dco_decode_list_category(dynamic raw);

  @protected
  List<Chapter> dco_decode_list_chapter(dynamic raw);

  @protected
  List<ComicSimple> dco_decode_list_comic_simple(dynamic raw);

  @protected
  List<ImageInfo> dco_decode_list_image_info(dynamic raw);

  @protected
  List<ModuleInfo> dco_decode_list_module_info(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<PropertyItem> dco_decode_list_property_item(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  ModuleInfo dco_decode_module_info(dynamic raw);

  @protected
  Map<String, String>? dco_decode_opt_Map_String_String_None(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PageInfo dco_decode_page_info(dynamic raw);

  @protected
  PropertyItem dco_decode_property_item(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  Category sse_decode_category(SseDeserializer deserializer);

  @protected
  Chapter sse_decode_chapter(SseDeserializer deserializer);

  @protected
  ChapterImages sse_decode_chapter_images(SseDeserializer deserializer);

  @protected
  ComicDetail sse_decode_comic_detail(SseDeserializer deserializer);

  @protected
  ComicListResponse sse_decode_comic_list_response(
    SseDeserializer deserializer,
  );

  @protected
  ComicSimple sse_decode_comic_simple(SseDeserializer deserializer);

  @protected
  HttpResponseDto sse_decode_http_response_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ImageInfo sse_decode_image_info(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Category> sse_decode_list_category(SseDeserializer deserializer);

  @protected
  List<Chapter> sse_decode_list_chapter(SseDeserializer deserializer);

  @protected
  List<ComicSimple> sse_decode_list_comic_simple(SseDeserializer deserializer);

  @protected
  List<ImageInfo> sse_decode_list_image_info(SseDeserializer deserializer);

  @protected
  List<ModuleInfo> sse_decode_list_module_info(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<PropertyItem> sse_decode_list_property_item(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  ModuleInfo sse_decode_module_info(SseDeserializer deserializer);

  @protected
  Map<String, String>? sse_decode_opt_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PageInfo sse_decode_page_info(SseDeserializer deserializer);

  @protected
  PropertyItem sse_decode_property_item(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_category(Category self, SseSerializer serializer);

  @protected
  void sse_encode_chapter(Chapter self, SseSerializer serializer);

  @protected
  void sse_encode_chapter_images(ChapterImages self, SseSerializer serializer);

  @protected
  void sse_encode_comic_detail(ComicDetail self, SseSerializer serializer);

  @protected
  void sse_encode_comic_list_response(
    ComicListResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_comic_simple(ComicSimple self, SseSerializer serializer);

  @protected
  void sse_encode_http_response_dto(
    HttpResponseDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_image_info(ImageInfo self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_category(List<Category> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chapter(List<Chapter> self, SseSerializer serializer);

  @protected
  void sse_encode_list_comic_simple(
    List<ComicSimple> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_image_info(
    List<ImageInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_module_info(
    List<ModuleInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_property_item(
    List<PropertyItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_module_info(ModuleInfo self, SseSerializer serializer);

  @protected
  void sse_encode_opt_Map_String_String_None(
    Map<String, String>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_page_info(PageInfo self, SseSerializer serializer);

  @protected
  void sse_encode_property_item(PropertyItem self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
