// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// MD5 哈希
String cryptoMd5({required String data}) =>
    RustLib.instance.api.crateApiCryptoApiCryptoMd5(data: data);

/// SHA256 哈希
String cryptoSha256({required String data}) =>
    RustLib.instance.api.crateApiCryptoApiCryptoSha256(data: data);

/// SHA512 哈希
String cryptoSha512({required String data}) =>
    RustLib.instance.api.crateApiCryptoApiCryptoSha512(data: data);

/// Base64 编码
String cryptoBase64Encode({required String data}) =>
    RustLib.instance.api.crateApiCryptoApiCryptoBase64Encode(data: data);

/// Base64 解码
String cryptoBase64Decode({required String data}) =>
    RustLib.instance.api.crateApiCryptoApiCryptoBase64Decode(data: data);

/// Hex 编码
String cryptoHexEncode({required String data}) =>
    RustLib.instance.api.crateApiCryptoApiCryptoHexEncode(data: data);

/// Hex 解码
String cryptoHexDecode({required String data}) =>
    RustLib.instance.api.crateApiCryptoApiCryptoHexDecode(data: data);

/// MD5 哈希（字节数组）
String cryptoMd5Bytes({required List<int> data}) =>
    RustLib.instance.api.crateApiCryptoApiCryptoMd5Bytes(data: data);

/// SHA256 哈希（字节数组）
String cryptoSha256Bytes({required List<int> data}) =>
    RustLib.instance.api.crateApiCryptoApiCryptoSha256Bytes(data: data);
