// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// 发送 HTTP GET 请求
Future<HttpResponseDto> httpGet({
  required String url,
  required Map<String, String> headers,
}) => RustLib.instance.api.crateApiHttpApiHttpGet(url: url, headers: headers);

/// 发送 HTTP POST 请求
Future<HttpResponseDto> httpPost({
  required String url,
  required Map<String, String> headers,
  String? body,
}) => RustLib.instance.api.crateApiHttpApiHttpPost(
  url: url,
  headers: headers,
  body: body,
);

/// 发送自定义 HTTP 请求
Future<HttpResponseDto> httpRequest({
  required String url,
  required String method,
  required Map<String, String> headers,
  String? body,
  required BigInt timeoutSecs,
}) => RustLib.instance.api.crateApiHttpApiHttpRequest(
  url: url,
  method: method,
  headers: headers,
  body: body,
  timeoutSecs: timeoutSecs,
);

/// 下载文件
Future<Uint8List> httpDownload({
  required String url,
  required Map<String, String> headers,
}) => RustLib.instance.api.crateApiHttpApiHttpDownload(
  url: url,
  headers: headers,
);

/// HTTP 响应 DTO（用于 Flutter）
class HttpResponseDto {
  final int status;
  final Map<String, String> headers;
  final String body;
  final String contentType;

  const HttpResponseDto({
    required this.status,
    required this.headers,
    required this.body,
    required this.contentType,
  });

  @override
  int get hashCode =>
      status.hashCode ^ headers.hashCode ^ body.hashCode ^ contentType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HttpResponseDto &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          headers == other.headers &&
          body == other.body &&
          contentType == other.contentType;
}
