// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 初始化应用
///
/// 在 Flutter 启动时调用，传入应用根目录路径
Future<void> initApplication({required String rootPath}) =>
    RustLib.instance.api.crateApiInitInitApplication(rootPath: rootPath);

/// 获取应用是否已初始化
bool isInitialized() => RustLib.instance.api.crateApiInitIsInitialized();

/// 获取应用根目录
String? getRootPath() => RustLib.instance.api.crateApiInitGetRootPath();

/// 获取模块目录
String? getModulesDir() => RustLib.instance.api.crateApiInitGetModulesDir();

/// 获取缓存目录
String? getCacheDir() => RustLib.instance.api.crateApiInitGetCacheDir();
