// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../modules/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_module_manager`, `init_module_manager`

/// 获取所有已注册的模块列表
Future<List<ModuleInfo>> getModules() =>
    RustLib.instance.api.crateApiModuleApiGetModules();

/// 扫描并注册所有模块
Future<List<ModuleInfo>> scanAndRegisterModules() =>
    RustLib.instance.api.crateApiModuleApiScanAndRegisterModules();

/// 注册单个模块
Future<ModuleInfo> registerModule({required String moduleId}) =>
    RustLib.instance.api.crateApiModuleApiRegisterModule(moduleId: moduleId);

/// 加载模块
Future<void> loadModule({required String moduleId}) =>
    RustLib.instance.api.crateApiModuleApiLoadModule(moduleId: moduleId);

/// 卸载模块
Future<void> unloadModule({required String moduleId}) =>
    RustLib.instance.api.crateApiModuleApiUnloadModule(moduleId: moduleId);

/// 启用/禁用模块
Future<void> setModuleEnabled({
  required String moduleId,
  required bool enabled,
}) => RustLib.instance.api.crateApiModuleApiSetModuleEnabled(
  moduleId: moduleId,
  enabled: enabled,
);

/// 获取模块的分类列表
Future<List<Category>> getCategories({required String moduleId}) =>
    RustLib.instance.api.crateApiModuleApiGetCategories(moduleId: moduleId);

/// 获取漫画列表
Future<ComicListResponse> getComicList({
  required String moduleId,
  required String categoryId,
  required int page,
}) => RustLib.instance.api.crateApiModuleApiGetComicList(
  moduleId: moduleId,
  categoryId: categoryId,
  page: page,
);

/// 获取漫画详情
Future<ComicDetail> getComicDetail({
  required String moduleId,
  required String comicId,
}) => RustLib.instance.api.crateApiModuleApiGetComicDetail(
  moduleId: moduleId,
  comicId: comicId,
);

/// 获取章节图片
Future<ChapterImages> getChapterImages({
  required String moduleId,
  required String comicId,
  required String chapterId,
}) => RustLib.instance.api.crateApiModuleApiGetChapterImages(
  moduleId: moduleId,
  comicId: comicId,
  chapterId: chapterId,
);

/// 搜索漫画
Future<ComicListResponse> searchComics({
  required String moduleId,
  required String keyword,
  required int page,
}) => RustLib.instance.api.crateApiModuleApiSearchComics(
  moduleId: moduleId,
  keyword: keyword,
  page: page,
);

/// 调用模块的任意函数（高级 API）
Future<String> callModuleFunction({
  required String moduleId,
  required String funcName,
  required String argsJson,
}) => RustLib.instance.api.crateApiModuleApiCallModuleFunction(
  moduleId: moduleId,
  funcName: funcName,
  argsJson: argsJson,
);
