// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `init_proxy`

/// 设置代理
///
/// # 参数
/// - `url`: 代理 URL，支持 http:// 和 socks5:// 协议。如果为空字符串或 None，则清除代理。
Future<void> setProxy({String? url}) =>
    RustLib.instance.api.crateApiProxyApiSetProxy(url: url);

/// 获取当前代理设置
Future<String?> getProxy() => RustLib.instance.api.crateApiProxyApiGetProxy();

/// 清除代理设置
Future<void> clearProxy() => RustLib.instance.api.crateApiProxyApiClearProxy();
