// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 漫画分类
class Category {
  final String id;
  final String name;
  final String? cover;

  const Category({required this.id, required this.name, this.cover});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ cover.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Category &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          cover == other.cover;
}

/// 章节信息
class Chapter {
  final String id;
  final String title;
  final String? updateTime;

  const Chapter({required this.id, required this.title, this.updateTime});

  @override
  int get hashCode => id.hashCode ^ title.hashCode ^ updateTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Chapter &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          updateTime == other.updateTime;
}

/// 章节图片列表
class ChapterImages {
  final String chapterId;
  final List<ImageInfo> images;

  const ChapterImages({required this.chapterId, required this.images});

  @override
  int get hashCode => chapterId.hashCode ^ images.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterImages &&
          runtimeType == other.runtimeType &&
          chapterId == other.chapterId &&
          images == other.images;
}

/// 漫画详情
class ComicDetail {
  final String id;
  final String title;
  final String cover;
  final String? author;
  final String? description;
  final String? status;
  final List<String> tags;
  final List<Chapter> chapters;
  final String? updateTime;

  const ComicDetail({
    required this.id,
    required this.title,
    required this.cover,
    this.author,
    this.description,
    this.status,
    required this.tags,
    required this.chapters,
    this.updateTime,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      cover.hashCode ^
      author.hashCode ^
      description.hashCode ^
      status.hashCode ^
      tags.hashCode ^
      chapters.hashCode ^
      updateTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComicDetail &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          cover == other.cover &&
          author == other.author &&
          description == other.description &&
          status == other.status &&
          tags == other.tags &&
          chapters == other.chapters &&
          updateTime == other.updateTime;
}

/// 漫画列表响应
class ComicListResponse {
  final List<ComicSimple> comics;
  final PageInfo pageInfo;

  const ComicListResponse({required this.comics, required this.pageInfo});

  @override
  int get hashCode => comics.hashCode ^ pageInfo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComicListResponse &&
          runtimeType == other.runtimeType &&
          comics == other.comics &&
          pageInfo == other.pageInfo;
}

/// 漫画基本信息（列表项）
class ComicSimple {
  final String id;
  final String title;
  final String cover;
  final String? author;
  final String? updateInfo;

  const ComicSimple({
    required this.id,
    required this.title,
    required this.cover,
    this.author,
    this.updateInfo,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      cover.hashCode ^
      author.hashCode ^
      updateInfo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComicSimple &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          cover == other.cover &&
          author == other.author &&
          updateInfo == other.updateInfo;
}

/// 图片信息
class ImageInfo {
  final String url;
  final int? width;
  final int? height;
  final Map<String, String>? headers;

  const ImageInfo({required this.url, this.width, this.height, this.headers});

  @override
  int get hashCode =>
      url.hashCode ^ width.hashCode ^ height.hashCode ^ headers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageInfo &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          width == other.width &&
          height == other.height &&
          headers == other.headers;
}

/// 模块信息
class ModuleInfo {
  final String id;
  final String name;
  final String version;
  final String description;
  final bool enabled;

  const ModuleInfo({
    required this.id,
    required this.name,
    required this.version,
    required this.description,
    required this.enabled,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      version.hashCode ^
      description.hashCode ^
      enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModuleInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          version == other.version &&
          description == other.description &&
          enabled == other.enabled;
}

/// 分页信息
class PageInfo {
  final int page;
  final int pageSize;
  final int? total;
  final bool hasMore;

  const PageInfo({
    required this.page,
    required this.pageSize,
    this.total,
    required this.hasMore,
  });

  @override
  int get hashCode =>
      page.hashCode ^ pageSize.hashCode ^ total.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageInfo &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          pageSize == other.pageSize &&
          total == other.total &&
          hasMore == other.hasMore;
}
